# 使用 DPDK 标准构建系统的 Makefile
# 需要设置 RTE_SDK 环境变量

include $(RTE_SDK)/mk/rte.vars.mk

# 应用程序名称
APP = dpdk_filter

# 源文件
SRCS-y := main.c

# CFLAGS
CFLAGS += -O3

# 包含 DPDK makefile
include $(RTE_SDK)/mk/rte.extapp.mk
